### ISSUE TITLE
Fix suggestion for Error "Failed to create directory" during download

### ISSUE THREAD

**Issue by realpablodias** [tknorris/tknorris-beta-repo#66] opened 2017-02-27 13:05 UTC
Hi there –

I'm running SALTS (2.0.150) on a Rpi2 + LibreElec (Kodi Krypton) and maybe found a bug while trying to download movies. It happens with Openelec too.

The thing is that `xbmcvfs.exists(path)` call returned false for 90% of movies I tried – I think movies with no spaces in their names were working, didn't try to find a pattern.

I edited the file **addons/script.module.tknorris.shared/lib/utils.py** changing the line **144**

**FROM:**
`path = xbmc.makeLegalFilename(path)`

**TO:**
`path = xbmc.translatePath(path).decode("utf-8")`

Now I'm able to download. Does it make sense?
I could not find a repo to send a PR. Please let me know if you want me to do that.

Thanks for your work on this add-on!

**Comment by tknorris** [comment] 2017-02-27 15:07
Thanks, I'll take a look. xbmcvfs should not require a translatePath, but if it makes it work, I'll change it.

**Comment by tknorris** [comment] 2017-02-27 16:21
Fix committed. Note I can't reproduce the issue on Ubuntu + Kodi 17, so we'll just have to see how it works out.

**Closed by tknorris** 2017-02-27 16:21 UTC
